server:
  port: 8989
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/youyiguan?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123123
  thymeleaf:
    cache: false
    check-template-location: false
  data:
    redis:
      host: ${youyiguan.redis.host}
      port: ${youyiguan.redis.port}
      database: ${youyiguan.redis.database}
mybatis:
  mapper-locations: classpath:mapper/*.xml